module.exports = {
  USER: 'USER',
  CONFERENCE: 'CONFERENCE',
  TEAM: 'TEAM',
  MEMBER: 'MEMBER',
  CATEGORY: 'CATEGORY',
  REASON: 'REASON',
  TRANSACTION: 'TRANSACTION',
  ACTIVITY: 'ACTIVITY',
  ACTIVITY_RESULT: 'ACTIVITY_RESULT'
};